title = "Ben O'Neill"
baseURL = 'https://oneill.sh/'
languageCode = 'en-us'
theme = 'not-much'
copyright = "Â© {year} Ben O'Neill <ben@oneill.sh>. All rights reserved."
enableRobotsTXT = true

[pagination]
  pagerSize = 20
  centerTheme = true
  showMenuItems = true

[params]
  showPostsSummary = false
  palette = "eink"

[menu]
  [[menu.main]]
    identifier = "apps"
    name = "Apps"
    url = "/apps"
  [[menu.main]]
    identifier = "bookmarks"
    name = "Bookmarks"
    url = "/bookmarks"
  [[menu.main]]
    identifier = "library"
    name = "Library"
    url = "/library"
